language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install "coverage==3.7.1" coveralls "mock>=1.0.1"

# command to run tests
script:
  - python manage.py test
  - coverage run manage.py test notifyAll
after_success:
  - coverage report
  - coveralls